# Generated by Django 4.2.30 on 2026-06-19 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='granted_by',
            field=models.ForeignKey(blank=True, db_column='granted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userpermissions_granted_by_set', to='users.users'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissions'),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.users'),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='granted_by',
            field=models.ForeignKey(blank=True, db_column='granted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.users'),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissions'),
        ),
        migrations.AddField(
            model_name='resourceaccesspolicies',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissionresources'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissionactions'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissionresources'),
        ),
        migrations.AddField(
            model_name='permissiongroupmembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissiongroups'),
        ),
        migrations.AddField(
            model_name='permissiongroupmembers',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissions'),
        ),
        migrations.AddField(
            model_name='permissionauditlogs',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissionactions'),
        ),
        migrations.AddField(
            model_name='permissionauditlogs',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissions'),
        ),
        migrations.AddField(
            model_name='permissionauditlogs',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissionresources'),
        ),
        migrations.AddField(
            model_name='permissionauditlogs',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permissionauditlogs_target_user_set', to='users.users'),
        ),
        migrations.AddField(
            model_name='permissionauditlogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.users'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermissions',
            unique_together={('user', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermissions',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='permissions',
            unique_together={('resource', 'action')},
        ),
        migrations.AlterUniqueTogether(
            name='permissiongroupmembers',
            unique_together={('group', 'permission')},
        ),
    ]
