# Generated by Django 4.2.30 on 2026-06-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionactions',
            options={'managed': True, 'verbose_name': 'សកម្មភាពសិទ្ធិ', 'verbose_name_plural': 'សកម្មភាពសិទ្ធិ'},
        ),
        migrations.AlterModelOptions(
            name='permissionauditlogs',
            options={'managed': True, 'verbose_name': 'កំណត់ហេតុត្រួតពិនិត្យសិទ្ធិ', 'verbose_name_plural': 'កំណត់ហេតុត្រួតពិនិត្យសិទ្ធិ'},
        ),
        migrations.AlterModelOptions(
            name='permissiongroupmembers',
            options={'managed': True, 'verbose_name': 'សមាជិកក្រុមសិទ្ធិ', 'verbose_name_plural': 'សមាជិកក្រុមសិទ្ធិ'},
        ),
        migrations.AlterModelOptions(
            name='permissiongroups',
            options={'managed': True, 'verbose_name': 'ក្រុមសិទ្ធិ', 'verbose_name_plural': 'ក្រុមសិទ្ធិ'},
        ),
        migrations.AlterModelOptions(
            name='permissionresources',
            options={'managed': True, 'verbose_name': 'ធនធានសិទ្ធិ', 'verbose_name_plural': 'ធនធានសិទ្ធិ'},
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'managed': True, 'verbose_name': 'សិទ្ធិ', 'verbose_name_plural': 'សិទ្ធិ'},
        ),
        migrations.AlterModelOptions(
            name='resourceaccesspolicies',
            options={'managed': True, 'verbose_name': 'គោលការណ៍ចូលប្រើធនធាន', 'verbose_name_plural': 'គោលការណ៍ចូលប្រើធនធាន'},
        ),
        migrations.AlterModelOptions(
            name='rolepermissions',
            options={'managed': True, 'verbose_name': 'សិទ្ធិតាមតួនាទី', 'verbose_name_plural': 'សិទ្ធិតាមតួនាទី'},
        ),
        migrations.AlterModelOptions(
            name='userpermissions',
            options={'managed': True, 'verbose_name': 'សិទ្ធិអ្នកប្រើប្រាស់', 'verbose_name_plural': 'សិទ្ធិអ្នកប្រើប្រាស់'},
        ),
    ]
