# Generated by Django 4.2.30 on 2026-06-19 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permissions', '0003_alter_permissionactions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionactions',
            name='action_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='កូដសកម្មភាព'),
        ),
        migrations.AlterField(
            model_name='permissionactions',
            name='action_level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='កម្រិតសកម្មភាព'),
        ),
        migrations.AlterField(
            model_name='permissionactions',
            name='action_name',
            field=models.CharField(max_length=100, verbose_name='ឈ្មោះសកម្មភាព'),
        ),
        migrations.AlterField(
            model_name='permissionactions',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='permissionactions',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='permissionactions',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='កំពុងប្រើប្រាស់'),
        ),
        migrations.AlterField(
            model_name='permissionactions',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissionactions', verbose_name='សកម្មភាព'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='action_type',
            field=models.CharField(max_length=30, verbose_name='ប្រភេទសកម្មភាព'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='អាសយដ្ឋាន IP'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='is_success',
            field=models.BooleanField(blank=True, null=True, verbose_name='ជោគជ័យ'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='new_value',
            field=models.TextField(blank=True, null=True, verbose_name='តម្លៃថ្មី'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='old_value',
            field=models.TextField(blank=True, null=True, verbose_name='តម្លៃចាស់'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissions', verbose_name='សិទ្ធិ'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='មូលហេតុ'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissionresources', verbose_name='ធនធាន'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='target_role',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='តួនាទីត្រូវប៉ះពាល់'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permissionauditlogs_target_user_set', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកប្រើប្រាស់ត្រូវប៉ះពាល់'),
        ),
        migrations.AlterField(
            model_name='permissionauditlogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកប្រើប្រាស់'),
        ),
    ]
