# Generated by Django 4.2.30 on 2026-06-19 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_alter_permissionactions_action_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroupmembers',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='permissiongroupmembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissiongroups', verbose_name='ក្រុមសិទ្ធិ'),
        ),
        migrations.AlterField(
            model_name='permissiongroupmembers',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissions', verbose_name='សិទ្ធិ'),
        ),
        migrations.AlterField(
            model_name='permissiongroups',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='permissiongroups',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='permissiongroups',
            name='display_order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='លំដាប់បង្ហាញ'),
        ),
        migrations.AlterField(
            model_name='permissiongroups',
            name='group_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='កូដក្រុម'),
        ),
        migrations.AlterField(
            model_name='permissiongroups',
            name='group_name',
            field=models.CharField(max_length=150, verbose_name='ឈ្មោះក្រុម'),
        ),
        migrations.AlterField(
            model_name='permissiongroups',
            name='group_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ប្រភេទក្រុម'),
        ),
        migrations.AlterField(
            model_name='permissiongroups',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='រូបតំណាង'),
        ),
        migrations.AlterField(
            model_name='permissiongroups',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='កំពុងប្រើប្រាស់'),
        ),
        migrations.AlterField(
            model_name='permissiongroups',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
    ]
