# Generated by Django 4.2.30 on 2026-06-19 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permissions', '0005_alter_permissiongroupmembers_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionresources',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='permissionresources',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='permissionresources',
            name='display_order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='លំដាប់បង្ហាញ'),
        ),
        migrations.AlterField(
            model_name='permissionresources',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='រូបតំណាង'),
        ),
        migrations.AlterField(
            model_name='permissionresources',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='កំពុងប្រើប្រាស់'),
        ),
        migrations.AlterField(
            model_name='permissionresources',
            name='resource_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='កូដធនធាន'),
        ),
        migrations.AlterField(
            model_name='permissionresources',
            name='resource_name',
            field=models.CharField(max_length=150, verbose_name='ឈ្មោះធនធាន'),
        ),
        migrations.AlterField(
            model_name='permissionresources',
            name='resource_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ប្រភេទធនធាន'),
        ),
        migrations.AlterField(
            model_name='permissionresources',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissionactions', verbose_name='សកម្មភាព'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='កំពុងប្រើប្រាស់'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='permission_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះសិទ្ធិ'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissionresources', verbose_name='ធនធាន'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='resourceaccesspolicies',
            name='approval_role',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='តួនាទីអនុម័ត'),
        ),
        migrations.AlterField(
            model_name='resourceaccesspolicies',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='resourceaccesspolicies',
            name='default_access',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ការចូលប្រើលំនាំដើម'),
        ),
        migrations.AlterField(
            model_name='resourceaccesspolicies',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='កំពុងប្រើប្រាស់'),
        ),
        migrations.AlterField(
            model_name='resourceaccesspolicies',
            name='policy_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះគោលការណ៍'),
        ),
        migrations.AlterField(
            model_name='resourceaccesspolicies',
            name='policy_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ប្រភេទគោលការណ៍'),
        ),
        migrations.AlterField(
            model_name='resourceaccesspolicies',
            name='require_approval',
            field=models.BooleanField(blank=True, null=True, verbose_name='ត្រូវការការអនុម័ត'),
        ),
        migrations.AlterField(
            model_name='resourceaccesspolicies',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissionresources', verbose_name='ធនធាន'),
        ),
        migrations.AlterField(
            model_name='resourceaccesspolicies',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ពេលផ្តល់សិទ្ធិ'),
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='granted_by',
            field=models.ForeignKey(blank=True, db_column='granted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកផ្តល់សិទ្ធិ'),
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='កំពុងប្រើប្រាស់'),
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ'),
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissions', verbose_name='សិទ្ធិ'),
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='role',
            field=models.CharField(max_length=30, verbose_name='តួនាទី'),
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
    ]
