# Generated by Django 4.2.30 on 2026-06-19 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permissions', '0006_alter_permissionresources_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃផុតកំណត់'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='grant_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ប្រភេទផ្តល់សិទ្ធិ'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ពេលផ្តល់សិទ្ធិ'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='granted_by',
            field=models.ForeignKey(blank=True, db_column='granted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userpermissions_granted_by_set', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកផ្តល់សិទ្ធិ'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='កំពុងប្រើប្រាស់'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permissions.permissions', verbose_name='សិទ្ធិ'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='មូលហេតុ'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកប្រើប្រាស់'),
        ),
    ]
