# Generated by Django 4.2.30 on 2026-06-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'managed': True, 'verbose_name': 'វត្តមាន', 'verbose_name_plural': 'វត្តមាន'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'managed': True, 'verbose_name': 'សេចក្តីជូនដំណឹង', 'verbose_name_plural': 'សេចក្តីជូនដំណឹង'},
        ),
        migrations.AlterModelOptions(
            name='reportdaily',
            options={'managed': True, 'verbose_name': 'របាយការណ៍ប្រចាំថ្ងៃ', 'verbose_name_plural': 'របាយការណ៍ប្រចាំថ្ងៃ'},
        ),
    ]
