# Generated by Django 4.2.30 on 2026-06-19 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_activitylogs_options_alter_positions_options_and_more'),
        ('core', '0003_alter_academicperiods_options_and_more'),
        ('students', '0003_alter_awards_options_alter_classmonitors_options_and_more'),
        ('attendance', '0003_alter_attendance_options_alter_notifications_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears', verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(verbose_name='ថ្ងៃវត្តមាន'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms', verbose_name='ថ្នាក់រៀន'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='recorded_by_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_recorded_by_monitor_set', to='students.students', verbose_name='កត់ត្រាដោយប្រធានថ្នាក់'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='recorded_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='កត់ត្រាដោយគ្រូ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.CharField(max_length=10, verbose_name='សម័យ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=15, verbose_name='ស្ថានភាព'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='សិស្ស'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects', verbose_name='មុខវិជ្ជា'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
    ]
