# Generated by Django 4.2.30 on 2026-06-19 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_awards_academic_year_alter_awards_award_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0004_alter_attendance_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='is_read',
            field=models.BooleanField(verbose_name='បានអាន'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.TextField(verbose_name='សារ'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='related_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='លេខសម្គាល់ពាក់ព័ន្ធ'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='សិស្ស'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.CharField(max_length=150, verbose_name='ចំណងជើង'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(max_length=50, verbose_name='ប្រភេទ'),
        ),
        migrations.AlterField(
            model_name='reportdaily',
            name='content',
            field=models.TextField(verbose_name='មាតិកា'),
        ),
        migrations.AlterField(
            model_name='reportdaily',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='reportdaily',
            name='report_date',
            field=models.DateField(verbose_name='ថ្ងៃរបាយការណ៍'),
        ),
        migrations.AlterField(
            model_name='reportdaily',
            name='reported_by',
            field=models.ForeignKey(blank=True, db_column='reported_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='អ្នករាយការណ៍'),
        ),
        migrations.AlterField(
            model_name='reportdaily',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ចំណងជើង'),
        ),
        migrations.AlterField(
            model_name='reportdaily',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
    ]
