# Generated by Django 4.2.30 on 2026-07-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ម៉ោងយឺត'),
        ),
    ]
