# Generated by Django 4.2.30 on 2026-07-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_payrollrates_note'),
        ('students', '0014_multiplepermission_dropoutstudent'),
        ('attendance', '0007_attendance_late_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_absent_warned', models.IntegerField(default=0, verbose_name='កម្រិតព្រមានអវត្តមានចុងក្រោយ')),
                ('last_permission_warned', models.IntegerField(default=0, verbose_name='កម្រិតព្រមានច្បាប់ចុងក្រោយ')),
                ('last_late_warned', models.IntegerField(default=0, verbose_name='កម្រិតព្រមានយឺតចុងក្រោយ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='កាលបរិច្ឆេទកែប្រែ')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyears', verbose_name='ឆ្នាំសិក្សា')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students', verbose_name='សិស្ស')),
            ],
            options={
                'verbose_name': 'ការព្រមានវត្តមាន',
                'verbose_name_plural': 'ការព្រមានវត្តមាន',
                'db_table': 'attendance_warnings',
                'managed': True,
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
