# Generated by Django 4.2.30 on 2026-06-19 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('homework_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'final_scores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(max_length=30)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicperiods')),
            ],
            options={
                'db_table': 'scores',
                'managed': True,
            },
        ),
    ]
