# Generated by Django 4.2.30 on 2026-06-19 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scores', '0001_initial'),
        ('core', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='scores',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects'),
        ),
        migrations.AddField(
            model_name='finalscores',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicperiods'),
        ),
        migrations.AddField(
            model_name='finalscores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='finalscores',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects'),
        ),
        migrations.AlterUniqueTogether(
            name='scores',
            unique_together={('student', 'subject', 'period', 'score_type')},
        ),
        migrations.AlterUniqueTogether(
            name='finalscores',
            unique_together={('student', 'subject', 'period')},
        ),
    ]
