# Generated by Django 4.2.30 on 2026-06-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalscores',
            options={'managed': True, 'verbose_name': 'ពិន្ទុចុងក្រោយ', 'verbose_name_plural': 'ពិន្ទុចុងក្រោយ'},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'managed': True, 'verbose_name': 'ពិន្ទុ', 'verbose_name_plural': 'ពិន្ទុ'},
        ),
    ]
