# Generated by Django 4.2.30 on 2026-06-19 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_academicyears_created_at_and_more'),
        ('students', '0004_alter_enrollments_academic_year_and_more'),
        ('scores', '0003_alter_finalscores_options_alter_scores_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalscores',
            name='attendance_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ពិន្ទុវត្តមាន'),
        ),
        migrations.AlterField(
            model_name='finalscores',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='finalscores',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ពិន្ទុប្រឡង'),
        ),
        migrations.AlterField(
            model_name='finalscores',
            name='exercise_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ពិន្ទុលំហាត់'),
        ),
        migrations.AlterField(
            model_name='finalscores',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ពិន្ទុចុងក្រោយ'),
        ),
        migrations.AlterField(
            model_name='finalscores',
            name='homework_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ពិន្ទុការងារផ្ទះ'),
        ),
        migrations.AlterField(
            model_name='finalscores',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicperiods', verbose_name='រយៈពេលសិក្សា'),
        ),
        migrations.AlterField(
            model_name='finalscores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='សិស្ស'),
        ),
        migrations.AlterField(
            model_name='finalscores',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects', verbose_name='មុខវិជ្ជា'),
        ),
        migrations.AlterField(
            model_name='finalscores',
            name='total_activity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ពិន្ទុសកម្មភាពសរុប'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃប្រឡង'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicperiods', verbose_name='រយៈពេលសិក្សា'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='raw_score',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ពិន្ទុដើម'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='score_type',
            field=models.CharField(max_length=30, verbose_name='ប្រភេទពិន្ទុ'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='សិស្ស'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects', verbose_name='មុខវិជ្ជា'),
        ),
    ]
