# Generated by Django 4.2.30 on 2026-06-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_id_alter_users_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylogs',
            options={'managed': True, 'verbose_name': 'កំណត់ហេតុសកម្មភាព', 'verbose_name_plural': 'កំណត់ហេតុសកម្មភាព'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'managed': True, 'verbose_name': 'តួនាទី', 'verbose_name_plural': 'តួនាទី'},
        ),
        migrations.AlterModelOptions(
            name='staffpositions',
            options={'managed': True, 'verbose_name': 'តួនាទីបុគ្គលិក', 'verbose_name_plural': 'តួនាទីបុគ្គលិក'},
        ),
        migrations.AlterModelOptions(
            name='teachereducation',
            options={'managed': True, 'verbose_name': 'ការសិក្សារបស់គ្រូ', 'verbose_name_plural': 'ការសិក្សារបស់គ្រូ'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'managed': True, 'verbose_name': 'គ្រូ', 'verbose_name_plural': 'គ្រូ'},
        ),
        migrations.AlterModelOptions(
            name='teachersalaries',
            options={'managed': True, 'verbose_name': 'ប្រាក់ខែគ្រូ', 'verbose_name_plural': 'ប្រាក់ខែគ្រូ'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True, 'verbose_name': 'អ្នកប្រើប្រាស់', 'verbose_name_plural': 'អ្នកប្រើប្រាស់'},
        ),
    ]
