# Generated by Django 4.2.30 on 2026-06-19 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_enrollments_academic_year_and_more'),
        ('users', '0003_alter_activitylogs_options_alter_positions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='នាមខ្លួន'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='ភេទ'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='រូបថត'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='នាមត្រកូល'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='latin_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះឡាតាំង'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='monk_status',
            field=models.CharField(max_length=20, verbose_name='ឋានៈព្រះសង្ឃ'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ទូរស័ព្ទ'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃចូលបម្រើការ'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='status',
            field=models.CharField(max_length=20, verbose_name='ស្ថានភាព'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teacher_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='កូដគ្រូ'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='កំពុងប្រើប្រាស់'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ចូលប្រើចុងក្រោយ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password_hash',
            field=models.CharField(max_length=255, verbose_name='ពាក្យសម្ងាត់'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(max_length=20, verbose_name='តួនាទី'),
        ),
        migrations.AlterField(
            model_name='users',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='សិស្ស'),
        ),
        migrations.AlterField(
            model_name='users',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='គ្រូ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='ឈ្មោះអ្នកប្រើប្រាស់'),
        ),
    ]
