# Generated by Django 4.2.30 on 2026-06-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_teachers_created_at_alter_teachers_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='image_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='teachers/', verbose_name='រូបថត'),
        ),
    ]
