# Generated by Django 4.2.30 on 2026-06-19 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_academicperiods_academic_year_and_more'),
        ('users', '0005_alter_teachers_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylogs',
            name='action',
            field=models.CharField(max_length=50, verbose_name='សកម្មភាព'),
        ),
        migrations.AlterField(
            model_name='activitylogs',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='activitylogs',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='activitylogs',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='អាសយដ្ឋាន IP'),
        ),
        migrations.AlterField(
            model_name='activitylogs',
            name='record_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='លេខសម្គាល់កំណត់ត្រា'),
        ),
        migrations.AlterField(
            model_name='activitylogs',
            name='table_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ឈ្មោះតារាង'),
        ),
        migrations.AlterField(
            model_name='activitylogs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកប្រើប្រាស់'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.positions', verbose_name='តួនាទីមេ'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='title',
            field=models.CharField(max_length=100, verbose_name='ចំណងជើង'),
        ),
        migrations.AlterField(
            model_name='staffpositions',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='staffpositions',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបញ្ចប់'),
        ),
        migrations.AlterField(
            model_name='staffpositions',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.positions', verbose_name='តួនាទី'),
        ),
        migrations.AlterField(
            model_name='staffpositions',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃចាប់ផ្តើម'),
        ),
        migrations.AlterField(
            model_name='staffpositions',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='គ្រូ'),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='degree',
            field=models.CharField(max_length=100, verbose_name='សញ្ញាបត្រ'),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='education_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ប្រភេទការសិក្សា'),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='end_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ឆ្នាំបញ្ចប់'),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ជំនាញ'),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='institution',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='គ្រឹះស្ថាន'),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='is_completed',
            field=models.BooleanField(blank=True, null=True, verbose_name='បានបញ្ចប់'),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='កំណត់ចំណាំ'),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='start_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ឆ្នាំចាប់ផ្តើម'),
        ),
        migrations.AlterField(
            model_name='teachereducation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='គ្រូ'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='កូដគ្រូ'),
        ),
        migrations.AlterField(
            model_name='teachersalaries',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears', verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.AlterField(
            model_name='teachersalaries',
            name='calculated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ពេលគណនា'),
        ),
        migrations.AlterField(
            model_name='teachersalaries',
            name='period_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ឈ្មោះរយៈពេល'),
        ),
        migrations.AlterField(
            model_name='teachersalaries',
            name='rate_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ថ្លៃក្នុងមួយម៉ោង'),
        ),
        migrations.AlterField(
            model_name='teachersalaries',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects', verbose_name='មុខវិជ្ជា'),
        ),
        migrations.AlterField(
            model_name='teachersalaries',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='គ្រូ'),
        ),
        migrations.AlterField(
            model_name='teachersalaries',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ប្រាក់សរុប'),
        ),
        migrations.AlterField(
            model_name='teachersalaries',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ចំនួនម៉ោងសរុប'),
        ),
    ]
