# Generated by Django 4.2.30 on 2026-06-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_activitylogs_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='gender',
            field=models.CharField(choices=[('ប្រុស', 'ប្រុស'), ('ស្រី', 'ស្រី')], max_length=10, verbose_name='ភេទ'),
        ),
    ]
