# Generated by Django 4.2.30 on 2026-06-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_teachers_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='monk_status',
            field=models.CharField(choices=[('គ្រហស្ថ', 'គ្រហស្ថ (Layperson)'), ('សាមណេរ', 'សាមណេរ (Novice Monk)'), ('ភិក្ខុ', 'ភិក្ខុ (Fully Ordained Monk)'), ('ព្រះចៅអធិការ', 'ព្រះចៅអធិការ (Abbot)')], max_length=20, verbose_name='ឋានៈព្រះសង្ឃ'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='status',
            field=models.CharField(choices=[('សកម្ម', 'សកម្ម (Active)'), ('ឈប់សម្រាក', 'ឈប់សម្រាក (On Leave)'), ('ព្យួរការងារ', 'ព្យួរការងារ (Suspended)'), ('ឈប់ធ្វើការ', 'ឈប់ធ្វើការ (Resigned/Inactive)')], max_length=20, verbose_name='ស្ថានភាព'),
        ),
    ]
