# Generated by Django 4.2.30 on 2026-06-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_teachers_monk_status_alter_teachers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='monk_status',
            field=models.CharField(choices=[('គ្រហស្ថ', 'គ្រហស្ថ'), ('សាមណេរ', 'សាមណេរ'), ('ភិក្ខុ', 'ភិក្ខុ'), ('ដូនជី', 'ដូនជី')], max_length=20, verbose_name='ឋានៈព្រះសង្ឃ'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='status',
            field=models.CharField(choices=[('active', 'សកម្ម'), ('inactive', 'អសកម្ម / ឈប់ធ្វើការ')], max_length=20, verbose_name='ស្ថានភាព'),
        ),
    ]
