# Generated by Django 4.2.30 on 2026-06-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_teachers_monk_status_alter_teachers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='លេខសម្គាល់'),
        ),
    ]
