# Generated by Django 4.2.30 on 2026-06-22 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_users_id_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='កូដតាមដាន')),
                ('image_url', models.ImageField(blank=True, max_length=500, null=True, upload_to='pending_teachers/', verbose_name='រូបថត')),
                ('first_name', models.CharField(max_length=50, verbose_name='នាមខ្លួន')),
                ('last_name', models.CharField(max_length=50, verbose_name='នាមត្រកូល')),
                ('latin_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះឡាតាំង')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='ភេទ')),
                ('monk_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='ឋានៈព្រះសង្ឃ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='ទូរស័ព្ទ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃចូលបម្រើការ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ')),
                ('status', models.CharField(default='draft', max_length=20, verbose_name='ស្ថានភាព')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='ពេលត្រួតពិនិត្យ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកត្រួតពិនិត្យ')),
            ],
            options={
                'verbose_name': 'គ្រូកំពុងរង់ចាំ',
                'verbose_name_plural': 'គ្រូកំពុងរង់ចាំ',
                'db_table': 'pending_teachers',
                'managed': True,
            },
        ),
    ]
