# Generated by Django 4.2.30 on 2026-06-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_pendingteachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRegistrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ចំណងជើង (ឧ. ការជ្រើសរើសគ្រូប្រចាំឆ្នាំ ២០២៦)')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម')),
                ('end_date', models.DateField(verbose_name='ថ្ងៃផុតកំណត់')),
                ('is_active', models.BooleanField(default=True, verbose_name='កំពុងបើក')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'រដូវកាលដាក់ពាក្យធ្វើគ្រូ',
                'verbose_name_plural': 'រដូវកាលដាក់ពាក្យធ្វើគ្រូ',
                'db_table': 'teacher_registration_sessions',
                'managed': True,
            },
        ),
    ]
