# Generated by Django 4.2.30 on 2026-06-19 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookentries',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='yearbookentries',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.timeslots'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslots',
            unique_together={('session', 'slot_no')},
        ),
        migrations.AddField(
            model_name='teachingsessions',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms'),
        ),
        migrations.AddField(
            model_name='teachingsessions',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects'),
        ),
        migrations.AddField(
            model_name='teachingsessions',
            name='substitution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.schedulesubstitutions'),
        ),
        migrations.AddField(
            model_name='teachingsessions',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='teachingsessions',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.timeslots'),
        ),
        migrations.AddField(
            model_name='schoolcalendar',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms'),
        ),
        migrations.AddField(
            model_name='schoolcalendar',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='schedulesubstitutions',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms'),
        ),
        migrations.AddField(
            model_name='schedulesubstitutions',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedulesubstitutions_created_by_set', to='users.teachers'),
        ),
        migrations.AddField(
            model_name='schedulesubstitutions',
            name='new_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedulesubstitutions_new_subject_set', to='core.subjects'),
        ),
        migrations.AddField(
            model_name='schedulesubstitutions',
            name='new_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='schedulesubstitutions',
            name='original_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects'),
        ),
        migrations.AddField(
            model_name='schedulesubstitutions',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.timeslots'),
        ),
        migrations.AddField(
            model_name='payrates',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects'),
        ),
        migrations.AddField(
            model_name='kutis',
            name='pagoda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.pagodas'),
        ),
        migrations.AddField(
            model_name='documents',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.users'),
        ),
        migrations.AddField(
            model_name='classsubjects',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms'),
        ),
        migrations.AddField(
            model_name='classsubjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects'),
        ),
        migrations.AddField(
            model_name='classsubjects',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='classrooms',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='academicperiods',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears'),
        ),
        migrations.AddField(
            model_name='academicperiods',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicperiods'),
        ),
        migrations.AlterUniqueTogether(
            name='yearbookentries',
            unique_together={('academic_year', 'classroom', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('classroom', 'academic_year', 'day_no', 'time_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='teachingsessions',
            unique_together={('classroom', 'session_date', 'time_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='kutis',
            unique_together={('pagoda', 'kuti_name')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubjects',
            unique_together={('classroom', 'subject')},
        ),
    ]
