# Generated by Django 4.2.30 on 2026-06-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperiods',
            options={'managed': True, 'verbose_name': 'រយៈពេលសិក្សា', 'verbose_name_plural': 'រយៈពេលសិក្សា'},
        ),
        migrations.AlterModelOptions(
            name='academicyears',
            options={'managed': True, 'verbose_name': 'ឆ្នាំសិក្សា', 'verbose_name_plural': 'ឆ្នាំសិក្សា'},
        ),
        migrations.AlterModelOptions(
            name='classrooms',
            options={'managed': True, 'verbose_name': 'ថ្នាក់រៀន', 'verbose_name_plural': 'ថ្នាក់រៀន'},
        ),
        migrations.AlterModelOptions(
            name='classsubjects',
            options={'managed': True, 'verbose_name': 'មុខវិជ្ជាថ្នាក់', 'verbose_name_plural': 'មុខវិជ្ជាថ្នាក់'},
        ),
        migrations.AlterModelOptions(
            name='communes',
            options={'managed': True, 'verbose_name': 'ឃុំ', 'verbose_name_plural': 'ឃុំ'},
        ),
        migrations.AlterModelOptions(
            name='districts',
            options={'managed': True, 'verbose_name': 'ស្រុក/ខណ្ឌ', 'verbose_name_plural': 'ស្រុក/ខណ្ឌ'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'managed': True, 'verbose_name': 'ឯកសារ', 'verbose_name_plural': 'ឯកសារ'},
        ),
        migrations.AlterModelOptions(
            name='kutis',
            options={'managed': True, 'verbose_name': 'កុដិ', 'verbose_name_plural': 'កុដិ'},
        ),
        migrations.AlterModelOptions(
            name='nationalities',
            options={'managed': True, 'verbose_name': 'សញ្ជាតិ', 'verbose_name_plural': 'សញ្ជាតិ'},
        ),
        migrations.AlterModelOptions(
            name='pagodas',
            options={'managed': True, 'verbose_name': 'វត្ត', 'verbose_name_plural': 'វត្ត'},
        ),
        migrations.AlterModelOptions(
            name='paperheaders',
            options={'managed': True, 'verbose_name': 'ក្បាលក្រដាស', 'verbose_name_plural': 'ក្បាលក្រដាស'},
        ),
        migrations.AlterModelOptions(
            name='payrates',
            options={'managed': True, 'verbose_name': 'អត្រាប្រាក់ខែ', 'verbose_name_plural': 'អត្រាប្រាក់ខែ'},
        ),
        migrations.AlterModelOptions(
            name='provinces',
            options={'managed': True, 'verbose_name': 'ខេត្ត', 'verbose_name_plural': 'ខេត្ត'},
        ),
        migrations.AlterModelOptions(
            name='schedulesubstitutions',
            options={'managed': True, 'verbose_name': 'ការផ្លាស់ប្តូរកាលវិភាគ', 'verbose_name_plural': 'ការផ្លាស់ប្តូរកាលវិភាគ'},
        ),
        migrations.AlterModelOptions(
            name='schoolcalendar',
            options={'managed': True, 'verbose_name': 'ប្រតិទិនសាលា', 'verbose_name_plural': 'ប្រតិទិនសាលា'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'managed': True, 'verbose_name': 'មុខវិជ្ជា', 'verbose_name_plural': 'មុខវិជ្ជា'},
        ),
        migrations.AlterModelOptions(
            name='teachingsessions',
            options={'managed': True, 'verbose_name': 'សម័យបង្រៀន', 'verbose_name_plural': 'សម័យបង្រៀន'},
        ),
        migrations.AlterModelOptions(
            name='timeslots',
            options={'managed': True, 'verbose_name': 'ផ្ទាំងពេលវេលា', 'verbose_name_plural': 'ផ្ទាំងពេលវេលា'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'managed': True, 'verbose_name': 'កាលវិភាគ', 'verbose_name_plural': 'កាលវិភាគ'},
        ),
        migrations.AlterModelOptions(
            name='villages',
            options={'managed': True, 'verbose_name': 'ភូមិ', 'verbose_name_plural': 'ភូមិ'},
        ),
        migrations.AlterModelOptions(
            name='yearbookentries',
            options={'managed': True, 'verbose_name': 'សៀវភៅប្រចាំឆ្នាំ', 'verbose_name_plural': 'សៀវភៅប្រចាំឆ្នាំ'},
        ),
    ]
