# Generated by Django 4.2.30 on 2026-06-19 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_activitylogs_options_alter_positions_options_and_more'),
        ('core', '0003_alter_academicperiods_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyears',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='academicyears',
            name='end_date',
            field=models.DateField(verbose_name='ថ្ងៃបញ្ចប់'),
        ),
        migrations.AlterField(
            model_name='academicyears',
            name='is_current',
            field=models.BooleanField(verbose_name='ឆ្នាំសិក្សាបច្ចុប្បន្ន'),
        ),
        migrations.AlterField(
            model_name='academicyears',
            name='start_date',
            field=models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម'),
        ),
        migrations.AlterField(
            model_name='academicyears',
            name='year_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='class_name',
            field=models.CharField(max_length=50, verbose_name='ឈ្មោះថ្នាក់'),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='grade_level',
            field=models.SmallIntegerField(verbose_name='កម្រិតថ្នាក់'),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='គ្រូបន្ទុកថ្នាក់'),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='បន្ទប់'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='coefficient',
            field=models.SmallIntegerField(verbose_name='មេគុណ'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='កូដមុខវិជ្ជា'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(max_length=100, verbose_name='ឈ្មោះមុខវិជ្ជា'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='total_homework',
            field=models.IntegerField(blank=True, null=True, verbose_name='ការងារផ្ទះសរុប'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='total_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='ចំនួនម៉ោងសរុប'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='total_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='ពិន្ទុសរុប'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='total_time_exam',
            field=models.IntegerField(blank=True, null=True, verbose_name='រយៈពេលប្រឡងសរុប'),
        ),
    ]
