# Generated by Django 4.2.30 on 2026-06-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_academicyears_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagodas',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.communes'),
        ),
        migrations.AlterField(
            model_name='pagodas',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.districts'),
        ),
        migrations.AlterField(
            model_name='pagodas',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.provinces'),
        ),
        migrations.AlterField(
            model_name='pagodas',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.villages'),
        ),
        migrations.AlterField(
            model_name='paperheaders',
            name='logo_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='paper_headers/'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='image_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='yearbooks/'),
        ),
    ]
