# Generated by Django 4.2.30 on 2026-06-19 07:11

from django.db import migrations, models
import django.db.models.deletion


def backfill_geo_hierarchy(apps, schema_editor):
    Provinces = apps.get_model('core', 'Provinces')
    Districts = apps.get_model('core', 'Districts')
    Communes = apps.get_model('core', 'Communes')
    Villages = apps.get_model('core', 'Villages')

    province_codes = set(Provinces.objects.values_list('province_code', flat=True))
    district_codes = set(Districts.objects.values_list('district_code', flat=True))
    commune_codes = set(Communes.objects.values_list('commune_code', flat=True))

    unmatched = {'district': 0, 'commune': 0, 'village': 0}

    for district in Districts.objects.all():
        code = district.district_code[2:4]
        if code in province_codes:
            district.province_id = code
            district.save(update_fields=['province'])
        else:
            unmatched['district'] += 1

    for commune in Communes.objects.all():
        code = '00' + commune.commune_code[:4]
        if code in district_codes:
            commune.district_id = code
            commune.save(update_fields=['district'])
        else:
            unmatched['commune'] += 1

    for village in Villages.objects.all():
        code = village.village_code[:6]
        if code in commune_codes:
            village.commune_id = code
            village.save(update_fields=['commune'])
        else:
            unmatched['village'] += 1

    if any(unmatched.values()):
        print(f'\nGeo hierarchy backfill: unmatched rows left NULL -> {unmatched}')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pagodas_commune_alter_pagodas_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communes',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.districts'),
        ),
        migrations.AddField(
            model_name='districts',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.provinces'),
        ),
        migrations.AddField(
            model_name='villages',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.communes'),
        ),
        migrations.RunPython(backfill_geo_hierarchy, noop),
    ]
