# Generated by Django 4.2.30 on 2026-06-19 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_geo_hierarchy_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagodas',
            name='abbot_name',
            field=models.CharField(max_length=150, verbose_name='ឈ្មោះព្រះអធិការ'),
        ),
        migrations.AlterField(
            model_name='pagodas',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.communes', verbose_name='ឃុំ/សង្កាត់'),
        ),
        migrations.AlterField(
            model_name='pagodas',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='pagodas',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.districts', verbose_name='ស្រុក/ខណ្ឌ'),
        ),
        migrations.AlterField(
            model_name='pagodas',
            name='name',
            field=models.CharField(max_length=150, verbose_name='ឈ្មោះ'),
        ),
        migrations.AlterField(
            model_name='pagodas',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ទូរស័ព្ទ'),
        ),
        migrations.AlterField(
            model_name='pagodas',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.provinces', verbose_name='ខេត្ត/ក្រុង'),
        ),
        migrations.AlterField(
            model_name='pagodas',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.villages', verbose_name='ភូមិ'),
        ),
    ]
