# Generated by Django 4.2.30 on 2026-06-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pagoda_khmer_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kutis',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='kutis',
            name='kuti_name',
            field=models.CharField(max_length=30, verbose_name='ឈ្មោះកុដិ'),
        ),
        migrations.AlterField(
            model_name='kutis',
            name='manager_name',
            field=models.CharField(max_length=150, verbose_name='ឈ្មោះអ្នកគ្រប់គ្រង'),
        ),
        migrations.AlterField(
            model_name='kutis',
            name='pagoda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.pagodas', verbose_name='វត្ត'),
        ),
    ]
