# Generated by Django 4.2.30 on 2026-06-19 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_teachers_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0005_alter_students_image_url'),
        ('core', '0008_kuti_khmer_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicperiods',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears', verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.AlterField(
            model_name='academicperiods',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='academicperiods',
            name='end_date',
            field=models.DateField(verbose_name='ថ្ងៃបញ្ចប់'),
        ),
        migrations.AlterField(
            model_name='academicperiods',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ឈ្មោះ'),
        ),
        migrations.AlterField(
            model_name='academicperiods',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicperiods', verbose_name='មេ'),
        ),
        migrations.AlterField(
            model_name='academicperiods',
            name='period_number',
            field=models.SmallIntegerField(verbose_name='លេខរយៈពេល'),
        ),
        migrations.AlterField(
            model_name='academicperiods',
            name='period_type',
            field=models.CharField(max_length=15, verbose_name='ប្រភេទរយៈពេល'),
        ),
        migrations.AlterField(
            model_name='academicperiods',
            name='start_date',
            field=models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម'),
        ),
        migrations.AlterField(
            model_name='academicyears',
            name='end_date',
            field=models.DateField(help_text='ឧទាហរណ៍៖ 2025-07-30', verbose_name='ថ្ងៃបញ្ចប់'),
        ),
        migrations.AlterField(
            model_name='academicyears',
            name='start_date',
            field=models.DateField(help_text='ឧទាហរណ៍៖ 2024-09-01', verbose_name='ថ្ងៃចាប់ផ្តើម'),
        ),
        migrations.AlterField(
            model_name='classsubjects',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms', verbose_name='ថ្នាក់រៀន'),
        ),
        migrations.AlterField(
            model_name='classsubjects',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='classsubjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects', verbose_name='មុខវិជ្ជា'),
        ),
        migrations.AlterField(
            model_name='classsubjects',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='គ្រូ'),
        ),
        migrations.AlterField(
            model_name='communes',
            name='commune_code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='កូដឃុំ'),
        ),
        migrations.AlterField(
            model_name='communes',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.districts', verbose_name='ស្រុក/ខណ្ឌ'),
        ),
        migrations.AlterField(
            model_name='communes',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះឡាតាំង'),
        ),
        migrations.AlterField(
            model_name='communes',
            name='name_kh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះខ្មែរ'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='district_code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='កូដស្រុក/ខណ្ឌ'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះឡាតាំង'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='name_kh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះខ្មែរ'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.provinces', verbose_name='ខេត្ត/ក្រុង'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_category',
            field=models.CharField(max_length=50, verbose_name='ប្រភេទឯកសារ'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file_url',
            field=models.TextField(verbose_name='តំណឯកសារ'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=255, verbose_name='ចំណងជើង'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកបញ្ចូល'),
        ),
        migrations.AlterField(
            model_name='nationalities',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='nationalities',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ឈ្មោះ'),
        ),
        migrations.AlterField(
            model_name='paperheaders',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='paperheaders',
            name='doc_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ប្រភេទឯកសារ'),
        ),
        migrations.AlterField(
            model_name='paperheaders',
            name='footer_html',
            field=models.TextField(blank=True, null=True, verbose_name='បាតក្រដាស (HTML)'),
        ),
        migrations.AlterField(
            model_name='paperheaders',
            name='header_html',
            field=models.TextField(blank=True, null=True, verbose_name='ក្បាលក្រដាស (HTML)'),
        ),
        migrations.AlterField(
            model_name='paperheaders',
            name='is_default',
            field=models.BooleanField(blank=True, null=True, verbose_name='លំនាំដើម'),
        ),
        migrations.AlterField(
            model_name='paperheaders',
            name='logo_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='paper_headers/', verbose_name='រូបសញ្ញា'),
        ),
        migrations.AlterField(
            model_name='paperheaders',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ឈ្មោះ'),
        ),
        migrations.AlterField(
            model_name='paperheaders',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='payrates',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='payrates',
            name='currency',
            field=models.CharField(max_length=10, verbose_name='រូបិយប័ណ្ណ'),
        ),
        migrations.AlterField(
            model_name='payrates',
            name='effective_from',
            field=models.DateField(verbose_name='ថ្ងៃចូលជាធរមាន'),
        ),
        migrations.AlterField(
            model_name='payrates',
            name='is_active',
            field=models.BooleanField(verbose_name='កំពុងប្រើប្រាស់'),
        ),
        migrations.AlterField(
            model_name='payrates',
            name='rate_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ថ្លៃក្នុងមួយម៉ោង'),
        ),
        migrations.AlterField(
            model_name='payrates',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects', verbose_name='មុខវិជ្ជា'),
        ),
        migrations.AlterField(
            model_name='payrates',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះឡាតាំង'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='name_kh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះខ្មែរ'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='province_code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='កូដខេត្ត/ក្រុង'),
        ),
        migrations.AlterField(
            model_name='schedulesubstitutions',
            name='change_date',
            field=models.DateField(verbose_name='ថ្ងៃផ្លាស់ប្តូរ'),
        ),
        migrations.AlterField(
            model_name='schedulesubstitutions',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms', verbose_name='ថ្នាក់រៀន'),
        ),
        migrations.AlterField(
            model_name='schedulesubstitutions',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='schedulesubstitutions',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedulesubstitutions_created_by_set', to='users.teachers', verbose_name='អ្នកបង្កើត'),
        ),
        migrations.AlterField(
            model_name='schedulesubstitutions',
            name='new_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedulesubstitutions_new_subject_set', to='core.subjects', verbose_name='មុខវិជ្ជាថ្មី'),
        ),
        migrations.AlterField(
            model_name='schedulesubstitutions',
            name='new_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='គ្រូជំនួស'),
        ),
        migrations.AlterField(
            model_name='schedulesubstitutions',
            name='original_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects', verbose_name='មុខវិជ្ជាដើម'),
        ),
        migrations.AlterField(
            model_name='schedulesubstitutions',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='មូលហេតុ'),
        ),
        migrations.AlterField(
            model_name='schedulesubstitutions',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.timeslots', verbose_name='ផ្ទាំងពេលវេលា'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms', verbose_name='ថ្នាក់រៀន'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='color_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='កូដពណ៌'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបញ្ចប់'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='event_type',
            field=models.CharField(max_length=30, verbose_name='ប្រភេទព្រឹត្តិការណ៍'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='is_public',
            field=models.BooleanField(blank=True, null=True, verbose_name='សាធារណៈ'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='is_recurring',
            field=models.BooleanField(blank=True, null=True, verbose_name='កើតឡើងម្តងទៀត'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ទីតាំង'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='notify_days',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ជូនដំណឹងមុន (ថ្ងៃ)'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='អ្នករៀបចំ'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='recurring_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ប្រភេទកើតឡើងម្តងទៀត'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='start_date',
            field=models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='title',
            field=models.CharField(max_length=150, verbose_name='ចំណងជើង'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='teachingsessions',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms', verbose_name='ថ្នាក់រៀន'),
        ),
        migrations.AlterField(
            model_name='teachingsessions',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='teachingsessions',
            name='is_substitute',
            field=models.BooleanField(verbose_name='ជាការជំនួស'),
        ),
        migrations.AlterField(
            model_name='teachingsessions',
            name='session_date',
            field=models.DateField(verbose_name='ថ្ងៃបង្រៀន'),
        ),
        migrations.AlterField(
            model_name='teachingsessions',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects', verbose_name='មុខវិជ្ជា'),
        ),
        migrations.AlterField(
            model_name='teachingsessions',
            name='substitution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.schedulesubstitutions', verbose_name='ការផ្លាស់ប្តូរកាលវិភាគ'),
        ),
        migrations.AlterField(
            model_name='teachingsessions',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='គ្រូ'),
        ),
        migrations.AlterField(
            model_name='teachingsessions',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.timeslots', verbose_name='ផ្ទាំងពេលវេលា'),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='end_time',
            field=models.TimeField(verbose_name='ម៉ោងបញ្ចប់'),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='session',
            field=models.CharField(max_length=10, verbose_name='វេន'),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='slot_no',
            field=models.SmallIntegerField(verbose_name='លេខផ្ទាំង'),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='start_time',
            field=models.TimeField(verbose_name='ម៉ោងចាប់ផ្តើម'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears', verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms', verbose_name='ថ្នាក់រៀន'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day_no',
            field=models.SmallIntegerField(verbose_name='ថ្ងៃទី'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects', verbose_name='មុខវិជ្ជា'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.timeslots', verbose_name='ផ្ទាំងពេលវេលា'),
        ),
        migrations.AlterField(
            model_name='villages',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.communes', verbose_name='ឃុំ/សង្កាត់'),
        ),
        migrations.AlterField(
            model_name='villages',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះឡាតាំង'),
        ),
        migrations.AlterField(
            model_name='villages',
            name='name_kh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះខ្មែរ'),
        ),
        migrations.AlterField(
            model_name='villages',
            name='village_code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='កូដភូមិ'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears', verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms', verbose_name='ថ្នាក់រៀន'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='entry_type',
            field=models.CharField(max_length=30, verbose_name='ប្រភេទធាតុ'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃព្រឹត្តិការណ៍'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='image_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='yearbooks/', verbose_name='រូបភាព'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='សិស្ស'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='section_order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='លំដាប់ផ្នែក'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='title',
            field=models.CharField(max_length=150, verbose_name='ចំណងជើង'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='yearbookentries',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='អ្នកបញ្ចូល'),
        ),
    ]
