# Generated by Django 4.2.30 on 2026-06-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_academicperiods_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='កូដមុខវិជ្ជា'),
        ),
    ]
