# Generated by Django 4.2.30 on 2026-06-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_subjects_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='កម្រិតវប្បធម៌')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត')),
            ],
            options={
                'verbose_name': 'កម្រិតវប្បធម៌',
                'verbose_name_plural': 'កម្រិតវប្បធម៌',
                'db_table': 'education_levels',
                'managed': True,
            },
        ),
    ]
