# Generated by Django 4.2.30 on 2026-06-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_educationlevels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
    ]
