# Generated by Django 4.2.30 on 2026-06-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_classrooms_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsubjects',
            options={'managed': True, 'ordering': ['order', 'id'], 'verbose_name': 'មុខវិជ្ជាថ្នាក់', 'verbose_name_plural': 'មុខវិជ្ជាថ្នាក់'},
        ),
        migrations.AddField(
            model_name='classsubjects',
            name='order',
            field=models.IntegerField(default=0, verbose_name='លំដាប់'),
        ),
    ]
