# Generated by Django 4.2.30 on 2026-06-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_classsubjects_options_classsubjects_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='desks_per_row',
            field=models.SmallIntegerField(default=5, verbose_name='ចំនួនតុក្នុងមួយជួរ'),
        ),
    ]
