# Generated by Django 4.2.30 on 2026-06-28 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_teacherregistrationsession'),
        ('core', '0014_classrooms_desks_per_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=7, verbose_name='ខែ/ឆ្នាំ (ឧ. 2026-06)')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ម៉ោងសរុប')),
                ('total_teaching', models.IntegerField(default=0, verbose_name='ចំនួនបង្រៀនសរុប')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ចំនួនទឹកប្រាក់សរុប')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjects', verbose_name='មុខវិជ្ជា')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='គ្រូបង្រៀន')),
            ],
            options={
                'verbose_name': 'កំណត់ត្រាបើកប្រាក់ខែ',
                'verbose_name_plural': 'កំណត់ត្រាបើកប្រាក់ខែ',
                'db_table': 'payroll_records',
                'managed': True,
            },
        ),
    ]
