# Generated by Django 4.2.30 on 2026-07-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_teacherregistrationsession'),
        ('core', '0017_payrollrates_note'),
    ]

    operations = [

        migrations.AddField(
            model_name='schedulesubstitutions',
            name='original_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedulesubstitutions_original_teacher_set', to='users.teachers', verbose_name='គ្រូដើម'),
        ),
        migrations.AddField(
            model_name='schedulesubstitutions',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20, verbose_name='ស្ថានភាព'),
        ),
    ]
