# Generated by Django 4.2.30 on 2026-07-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_teacherregistrationsession'),
        ('core', '0017_payrollrates_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayrolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ម៉ោងសរុប')),
                ('total_teaching', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ចំនួនបង្រៀនសរុប')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ថ្លៃក្នុងមួយម៉ោង')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ចំនួនទឹកប្រាក់សរុប')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ')),
            ],
            options={
                'verbose_name': 'កំណត់ត្រាបើកប្រាក់ខែប្រចាំខែ',
                'verbose_name_plural': 'កំណត់ត្រាបើកប្រាក់ខែប្រចាំខែ',
                'db_table': 'monthly_payrolls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_teaching', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'payroll_rates',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='schedulesubstitutions',
            name='original_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedulesubstitutions_original_teacher_set', to='users.teachers', verbose_name='គ្រូដើម'),
        ),
        migrations.AddField(
            model_name='schedulesubstitutions',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20, verbose_name='ស្ថានភាព'),
        ),
    ]
