# Generated by Django 4.2.30 on 2026-06-19 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('users', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayyear',
            name='recorded_by',
            field=models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.users'),
        ),
        migrations.AddField(
            model_name='studentpayyear',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='studenteducation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.users'),
        ),
        migrations.AddField(
            model_name='monkpermissionlogs',
            name='performed_by',
            field=models.ForeignKey(blank=True, db_column='performed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='monkpermissionlogs',
            name='performed_by_monitor',
            field=models.ForeignKey(blank=True, db_column='performed_by_monitor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='monkpermissionlogs',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.monkpermission'),
        ),
        migrations.AddField(
            model_name='monkpermission',
            name='monk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='monkpermission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='monkpermission',
            name='reviewed_by_monitor',
            field=models.ForeignKey(blank=True, db_column='reviewed_by_monitor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='monkpermission_reviewed_by_monitor_set', to='students.students'),
        ),
        migrations.AddField(
            model_name='enrollments',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears'),
        ),
        migrations.AddField(
            model_name='enrollments',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms'),
        ),
        migrations.AddField(
            model_name='enrollments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='classmonitors',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears'),
        ),
        migrations.AddField(
            model_name='classmonitors',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms'),
        ),
        migrations.AddField(
            model_name='classmonitors',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='awards',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears'),
        ),
        migrations.AddField(
            model_name='awards',
            name='awarded_by',
            field=models.ForeignKey(blank=True, db_column='awarded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='awards',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AlterUniqueTogether(
            name='studentpayyear',
            unique_together={('student', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollments',
            unique_together={('student', 'classroom', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='classmonitors',
            unique_together={('classroom', 'academic_year', 'role')},
        ),
    ]
