# Generated by Django 4.2.30 on 2026-06-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awards',
            options={'managed': True, 'verbose_name': 'រង្វាន់', 'verbose_name_plural': 'រង្វាន់'},
        ),
        migrations.AlterModelOptions(
            name='classmonitors',
            options={'managed': True, 'verbose_name': 'ប្រធានថ្នាក់', 'verbose_name_plural': 'ប្រធានថ្នាក់'},
        ),
        migrations.AlterModelOptions(
            name='enrollments',
            options={'managed': True, 'verbose_name': 'ការចុះឈ្មោះចូលរៀន', 'verbose_name_plural': 'ការចុះឈ្មោះចូលរៀន'},
        ),
        migrations.AlterModelOptions(
            name='monkpermission',
            options={'managed': True, 'verbose_name': 'ច្បាប់ឈប់សម្រាក', 'verbose_name_plural': 'ច្បាប់ឈប់សម្រាក'},
        ),
        migrations.AlterModelOptions(
            name='monkpermissionlogs',
            options={'managed': True, 'verbose_name': 'កំណត់ហេតុច្បាប់ឈប់សម្រាក', 'verbose_name_plural': 'កំណត់ហេតុច្បាប់ឈប់សម្រាក'},
        ),
        migrations.AlterModelOptions(
            name='pendingstudents',
            options={'managed': True, 'verbose_name': 'សិស្សកំពុងរង់ចាំ', 'verbose_name_plural': 'សិស្សកំពុងរង់ចាំ'},
        ),
        migrations.AlterModelOptions(
            name='studenteducation',
            options={'managed': True, 'verbose_name': 'ការសិក្សារបស់សិស្ស', 'verbose_name_plural': 'ការសិក្សារបស់សិស្ស'},
        ),
        migrations.AlterModelOptions(
            name='studentpayyear',
            options={'managed': True, 'verbose_name': 'ការបង់ប្រាក់សិស្សប្រចាំឆ្នាំ', 'verbose_name_plural': 'ការបង់ប្រាក់សិស្សប្រចាំឆ្នាំ'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'managed': True, 'verbose_name': 'សិស្ស', 'verbose_name_plural': 'សិស្ស'},
        ),
    ]
