# Generated by Django 4.2.30 on 2026-06-19 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_academicyears_created_at_and_more'),
        ('students', '0003_alter_awards_options_alter_classmonitors_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears', verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms', verbose_name='ថ្នាក់រៀន'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='enrollment_date',
            field=models.DateField(verbose_name='ថ្ងៃចុះឈ្មោះ'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='សិស្ស'),
        ),
        migrations.AlterField(
            model_name='students',
            name='birth_pagoda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students_birth_pagoda_set', to='core.pagodas', verbose_name='វត្តកំណើត'),
        ),
        migrations.AlterField(
            model_name='students',
            name='birth_village_code',
            field=models.ForeignKey(blank=True, db_column='birth_village_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.villages', verbose_name='ភូមិកំណើត'),
        ),
        migrations.AlterField(
            model_name='students',
            name='chaya_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះឆាយា'),
        ),
        migrations.AlterField(
            model_name='students',
            name='chaya_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='លេខឆាយា'),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='students',
            name='current_pagoda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pagodas', verbose_name='វត្តកំពុងស្នាក់'),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃខែឆ្នាំកំណើត'),
        ),
        migrations.AlterField(
            model_name='students',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='កម្រិតវប្បធម៌'),
        ),
        migrations.AlterField(
            model_name='students',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃចូលរៀន'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='នាមខ្លួន'),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='ភេទ'),
        ),
        migrations.AlterField(
            model_name='students',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='រូបថត'),
        ),
        migrations.AlterField(
            model_name='students',
            name='kuti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.kutis', verbose_name='កុដិ'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='នាមត្រកូល'),
        ),
        migrations.AlterField(
            model_name='students',
            name='latin_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះឡាតាំង'),
        ),
        migrations.AlterField(
            model_name='students',
            name='monk_status',
            field=models.CharField(max_length=20, verbose_name='ឋានៈព្រះសង្ឃ'),
        ),
        migrations.AlterField(
            model_name='students',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.nationalities', verbose_name='សញ្ជាតិ'),
        ),
        migrations.AlterField(
            model_name='students',
            name='ordination_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបួស'),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ទូរស័ព្ទ'),
        ),
        migrations.AlterField(
            model_name='students',
            name='preceptor_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះព្រះឧបជ្ឈាយ៍'),
        ),
        migrations.AlterField(
            model_name='students',
            name='sanghatika_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='លេខសង្ឃាដិក'),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(max_length=20, verbose_name='ស្ថានភាព'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='កូដសិស្ស'),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
    ]
