# Generated by Django 4.2.30 on 2026-06-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_enrollments_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='students/', verbose_name='រូបថត'),
        ),
    ]
