# Generated by Django 4.2.30 on 2026-06-19 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_academicperiods_academic_year_and_more'),
        ('users', '0005_alter_teachers_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0005_alter_students_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears', verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='award_type',
            field=models.CharField(max_length=30, verbose_name='ប្រភេទរង្វាន់'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='awarded_by',
            field=models.ForeignKey(blank=True, db_column='awarded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='អ្នកប្រគល់'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='awarded_date',
            field=models.DateField(verbose_name='ថ្ងៃទទួលរង្វាន់'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ប្រភេទ'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='evidence_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='តំណភ័ស្តុតាង'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='rank',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ចំណាត់ថ្នាក់'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ស្ថានភាព'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='សិស្ស'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='title',
            field=models.CharField(max_length=150, verbose_name='ចំណងជើង'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='classmonitors',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears', verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.AlterField(
            model_name='classmonitors',
            name='appointed_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃតែងតាំង'),
        ),
        migrations.AlterField(
            model_name='classmonitors',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classrooms', verbose_name='ថ្នាក់រៀន'),
        ),
        migrations.AlterField(
            model_name='classmonitors',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='classmonitors',
            name='role',
            field=models.CharField(max_length=30, verbose_name='តួនាទី'),
        ),
        migrations.AlterField(
            model_name='classmonitors',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='សិស្ស'),
        ),
        migrations.AlterField(
            model_name='monkpermission',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='monkpermission',
            name='end_date',
            field=models.DateField(verbose_name='ថ្ងៃបញ្ចប់'),
        ),
        migrations.AlterField(
            model_name='monkpermission',
            name='monk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='ព្រះសង្ឃ'),
        ),
        migrations.AlterField(
            model_name='monkpermission',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='មូលហេតុ'),
        ),
        migrations.AlterField(
            model_name='monkpermission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ពេលត្រួតពិនិត្យ'),
        ),
        migrations.AlterField(
            model_name='monkpermission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='អ្នកត្រួតពិនិត្យ'),
        ),
        migrations.AlterField(
            model_name='monkpermission',
            name='reviewed_by_monitor',
            field=models.ForeignKey(blank=True, db_column='reviewed_by_monitor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='monkpermission_reviewed_by_monitor_set', to='students.students', verbose_name='ប្រធានថ្នាក់ត្រួតពិនិត្យ'),
        ),
        migrations.AlterField(
            model_name='monkpermission',
            name='start_date',
            field=models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម'),
        ),
        migrations.AlterField(
            model_name='monkpermission',
            name='status',
            field=models.CharField(max_length=20, verbose_name='ស្ថានភាព'),
        ),
        migrations.AlterField(
            model_name='monkpermission',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
        migrations.AlterField(
            model_name='monkpermissionlogs',
            name='action',
            field=models.CharField(max_length=30, verbose_name='សកម្មភាព'),
        ),
        migrations.AlterField(
            model_name='monkpermissionlogs',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='monkpermissionlogs',
            name='new_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ស្ថានភាពថ្មី'),
        ),
        migrations.AlterField(
            model_name='monkpermissionlogs',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='កំណត់ចំណាំ'),
        ),
        migrations.AlterField(
            model_name='monkpermissionlogs',
            name='old_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ស្ថានភាពចាស់'),
        ),
        migrations.AlterField(
            model_name='monkpermissionlogs',
            name='performed_by',
            field=models.ForeignKey(blank=True, db_column='performed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.teachers', verbose_name='អ្នកអនុវត្ត'),
        ),
        migrations.AlterField(
            model_name='monkpermissionlogs',
            name='performed_by_monitor',
            field=models.ForeignKey(blank=True, db_column='performed_by_monitor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='ប្រធានថ្នាក់អនុវត្ត'),
        ),
        migrations.AlterField(
            model_name='monkpermissionlogs',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.monkpermission', verbose_name='ច្បាប់ឈប់សម្រាក'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='អាសយដ្ឋាន'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃខែឆ្នាំកំណើត'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='នាមខ្លួន'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='ភេទ'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='នាមត្រកូល'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='pagoda_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះវត្ត'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ទូរស័ព្ទ'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ពេលត្រួតពិនិត្យ'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកត្រួតពិនិត្យ'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='status',
            field=models.CharField(max_length=20, verbose_name='ស្ថានភាព'),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='end_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ឆ្នាំបញ្ចប់'),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='institution',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='គ្រឹះស្ថាន'),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='level',
            field=models.CharField(max_length=100, verbose_name='កម្រិតវប្បធម៌'),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='កំណត់ចំណាំ'),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='start_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ឆ្នាំចាប់ផ្តើម'),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='សិស្ស'),
        ),
    ]
