# Generated by Django 4.2.30 on 2026-06-19 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_academicperiods_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_alter_awards_academic_year_alter_awards_award_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayyear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.academicyears', verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.AlterField(
            model_name='studentpayyear',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ប្រាក់ត្រូវបង់'),
        ),
        migrations.AlterField(
            model_name='studentpayyear',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ប្រាក់បានបង់'),
        ),
        migrations.AlterField(
            model_name='studentpayyear',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ប្រាក់នៅខ្វះ'),
        ),
        migrations.AlterField(
            model_name='studentpayyear',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='studentpayyear',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ'),
        ),
        migrations.AlterField(
            model_name='studentpayyear',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបង់ប្រាក់'),
        ),
        migrations.AlterField(
            model_name='studentpayyear',
            name='recorded_by',
            field=models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកកត់ត្រា'),
        ),
        migrations.AlterField(
            model_name='studentpayyear',
            name='status',
            field=models.CharField(max_length=20, verbose_name='ស្ថានភាព'),
        ),
        migrations.AlterField(
            model_name='studentpayyear',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students', verbose_name='សិស្ស'),
        ),
        migrations.AlterField(
            model_name='studentpayyear',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកែប្រែ'),
        ),
    ]
