# Generated by Django 4.2.30 on 2026-06-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_subjects_subject_code'),
        ('students', '0007_alter_studentpayyear_academic_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingstudents',
            name='pagoda_name',
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='birth_pagoda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pending_students_birth_pagoda_set', to='core.pagodas', verbose_name='វត្តកំណើត'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='birth_village_code',
            field=models.ForeignKey(blank=True, db_column='birth_village_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.villages', verbose_name='ភូមិកំណើត'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='chaya_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះឆាយា'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='chaya_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='លេខឆាយា'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='current_pagoda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pagodas', verbose_name='វត្តកំពុងស្នាក់'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='កម្រិតវប្បធម៌'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='kuti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.kutis', verbose_name='កុដិ'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='latin_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះឡាតាំង'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='monk_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ឋានៈព្រះសង្ឃ'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.nationalities', verbose_name='សញ្ជាតិ'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='ordination_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបួស'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='preceptor_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះព្រះឧបជ្ឈាយ៍'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='sanghatika_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='លេខសង្ឃាដិក'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='កូដតាមដាន'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ភេទ'),
        ),
        migrations.AlterField(
            model_name='pendingstudents',
            name='status',
            field=models.CharField(default='draft', max_length=20, verbose_name='ស្ថានភាព'),
        ),
    ]
