# Generated by Django 4.2.30 on 2026-06-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_pendingstudents_pagoda_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ចំណងជើង (ឧ. ឆ្នាំសិក្សា ២០២៦)')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម')),
                ('end_date', models.DateField(verbose_name='ថ្ងៃបញ្ចប់')),
                ('is_active', models.BooleanField(default=True, verbose_name='កំពុងបើក')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'រដូវកាលចុះឈ្មោះ',
                'verbose_name_plural': 'រដូវកាលចុះឈ្មោះ',
                'db_table': 'registration_sessions',
                'managed': True,
            },
        ),
    ]
