# Generated by Django 4.2.30 on 2026-06-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_educationlevels'),
        ('students', '0009_registrationsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.educationlevels', verbose_name='កម្រិតវប្បធម៌'),
        ),
    ]
