# Generated by Django 4.2.30 on 2026-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_students_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingstudents',
            name='image_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='pending_students/', verbose_name='រូបថត'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='new_birth_pagoda_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='វត្តកំណើត (ថ្មី)'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='new_current_pagoda_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='វត្តកំពុងស្នាក់ (ថ្មី)'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='new_kuti_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='កុដិ (ថ្មី)'),
        ),
        migrations.AddField(
            model_name='pendingstudents',
            name='new_nationality_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='សញ្ជាតិ (ថ្មី)'),
        ),
    ]
