# Generated by Django 4.2.30 on 2026-06-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_pendingstudents_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='កាលបរិច្ឆេទបង្កើត'),
        ),
    ]
