# Generated by Django 4.2.30 on 2026-06-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_students_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='desk_number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='លេខតុ'),
        ),
    ]
