# Generated by Django 4.2.30 on 2026-06-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_enrollments_desk_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='មូលហេតុ')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម')),
                ('end_date', models.DateField(verbose_name='ថ្ងៃបញ្ចប់')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='បានផ្ញើសាររំលឹក')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទបង្កើត')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students', verbose_name='សិស្ស')),
            ],
            options={
                'verbose_name': 'ច្បាប់ឈប់សម្រាកច្រើនថ្ងៃ',
                'verbose_name_plural': 'ច្បាប់ឈប់សម្រាកច្រើនថ្ងៃ',
                'db_table': 'multiple_permission',
            },
        ),
        migrations.CreateModel(
            name='DropoutStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='មូលហេតុ')),
                ('status', models.BooleanField(default=True, verbose_name='ស្ថានភាពឈប់រៀន')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទបង្កើត')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students', verbose_name='សិស្ស')),
            ],
            options={
                'verbose_name': 'សិស្សឈប់រៀន',
                'verbose_name_plural': 'សិស្សឈប់រៀន',
                'db_table': 'dropout',
            },
        ),
    ]
